name: Deploy ARM template to Azure Data Factory

on:
  push:
    branches:
      - main

run-name: Publish NPM - ${{ github.event.inputs.package }}
      
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest  
    environment: npm-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: verify package exists
        run: ls my_root/${{ github.event.inputs.package }}
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '20.x' 

      - name: npm install
        run: npm install
        
      - name: Install dependencies
        working-directory: my_root/${{ github.event.inputs.package }}
        run: npm install
                           
      - uses: actions/upload-artifact@v4
        with:
          name: adf-armtemplate
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
          include-hidden-files: false

  deploy:      
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: Download ARM template
        uses: actions/download-artifact@v4
        with:
          name: adf-armtemplate
          path: ${{ github.event.inputs.package }}

      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }} 
          dataFactoryName: ${{ secrets.AZURE_DATA_FACTORY }} 
          // template: './adf_publish/ARMTemplateForFactory.json'  # ARM template file path
          //parameters: './adf_publish/ARMTemplateParametersForFactory.json'  # Parameters file path
          //deploymentName: 'adf-deployment'
